<center> <h1>Numerical Python (NumPy)</h1> </center><br><hr>

In [ ]:
#Links 
# https://jakevdp.github.io/PythonDataScienceHandbook/02.01-understanding-data-types.html
# Difference between numpy array and python list?

In [1]:
import numpy as np

## Creating 1D Arrays

In [2]:
l = [1,2,3]
x = np.array(l)
x

array([1, 2, 3])

In [3]:
type(1)

int

In [4]:
print(type(1))

<class 'int'>


In [5]:
y = np.array([4,5,6])
type(y)

numpy.ndarray

In [6]:
print(x.shape)
print(y.shape)
print(x.dtype)
y.dtype

(3,)
(3,)
int64


dtype('int64')

In [7]:
# What is difference between *args and **kwargs?
def f(a,b,c=0,d=1,*args, **kwargs):
    print(a,b)
    print(args)
    print(kwargs)

    
f(2,3,4,5,6,7,8,name='CB',age='5')

2 3
(6, 7, 8)
{'name': 'CB', 'age': '5'}


In [8]:
foo = np.array(['n','u','m','p','y'], dtype=np.str)
foo.dtype # {little-endian, unicode, 8-bit} 
                                            # https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html

dtype('<U1')

In [9]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
[1,2,3,4]

[1, 2, 3, 4]

In [11]:
n = np.arange(0, 30, 2) # create an array of numbers between [0,30) with an interval of 2
n
print(n.ndim)

1


In [12]:
o = np.linspace(0, 10, 9) # create an array of 9 elements between [0,10]. Decide the interval according to n
o

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

## Creating 2D Arrays

In [13]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a)
print(a.shape)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [14]:
a.ndim

2

In [15]:
q = np.ones((3,2))
q

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
p = np.ones((3,2), int)
p

array([[1, 1],
       [1, 1],
       [1, 1]])

In [17]:
print(q.dtype)
print(p.dtype)

float64
int64


In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.eye((4),dtype=int) # Identity Matrix

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [20]:
print(np.diag(np.array([[1,2,3],[4,5,6],[7,8,9]]))) # Diagonal array
print(np.diag(p))

[1 5 9]
[1 1]


In [21]:
np.full((2,3), 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [22]:
# samples are from continous random distribution
t1=np.random.random((2,3))
print(t1)
t1.shape

[[0.04626018 0.35230539 0.35834173]
 [0.62713071 0.23490339 0.88494418]]


(2, 3)

In [23]:
np.diag((10,99,44))

array([[10,  0,  0],
       [ 0, 99,  0],
       [ 0,  0, 44]])

In [24]:
t1=np.diag((10,99,44)).flatten()
print(t1)
t1.shape

[10  0  0  0 99  0  0  0 44]


(9,)

## Reshaping VS Resizing

In [25]:
n = np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [26]:
n.shape

(15,)

In [27]:
l= n.reshape(3,5) # the product should match the number of total elements.It returns a copy.
print(l)
print(n)

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [28]:
o = np.linspace(0,10,9)
print(o)
l = o.resize(3,3) # Inplace as it will return None
print(l)
print(o)

[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.  ]
None
[[ 0.    1.25  2.5 ]
 [ 3.75  5.    6.25]
 [ 7.5   8.75 10.  ]]


### Stacking

In [29]:
np.stack([[1,2], [99,100], [-45, -47]], axis=1)#0)

array([[  1,  99, -45],
       [  2, 100, -47]])

In [30]:
np.vstack?
np.vstack([[1,2],[99,100],[-45,-47]])

array([[  1,   2],
       [ 99, 100],
       [-45, -47]])

In [31]:
np.hstack?
np.hstack([[1,2],[99,100],[-45,-47]])

array([  1,   2,  99, 100, -45, -47])

In [32]:
arr1=np.array([[1,2],[11,12]])
arr2=np.array([[3,4],[31,41]])
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4],
       [11, 12, 31, 41]])

In [ ]:
arr1

In [ ]:
arr3 = np.array([[1,11], [2,22], [3,33]])
arr4 = np.array([[2,22], [3,33], [4,44]])
np.vstack((arr3,arr4))

## Vectorized Operations

In [33]:
print("X:", x)
print("Y:", y)

X: [1 2 3]
Y: [4 5 6]


In [34]:
# Pointwise / Elementwise
print("X+Y:", x+y)
print("X*Y:", x*y)
print("X/Y:", x/y)
print("X**Y:", x**y)

X+Y: [5 7 9]
X*Y: [ 4 10 18]
X/Y: [0.25 0.4  0.5 ]
X**Y: [  1  32 729]


In [35]:
# Multiplication with a scalar
print(np.array([1,2,3]) * 3, "-- array * 3")
print("VS")
print(np.array([1,2,3] * 3), "-- list * 3")
print("VS")
print(np.repeat([1,2,3], 3), "-- repeat method of numpy array")

[3 6 9] -- array * 3
VS
[1 2 3 1 2 3 1 2 3] -- list * 3
VS
[1 1 1 2 2 2 3 3 3] -- repeat method of numpy array


In [36]:
# Dot Product
x.dot(y)

32

In [37]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

## Transposing

In [38]:
# Transpose
print(z.T)
print(z)

[[ 4 16]
 [ 5 25]
 [ 6 36]]
[[ 4  5  6]
 [16 25 36]]


In [39]:
print(z.shape, z.T.shape)

(2, 3) (3, 2)


In [40]:
l = [[1,2,3],[2,2,3],[9,0,8]]
q = np.array(l)
q

array([[1, 2, 3],
       [2, 2, 3],
       [9, 0, 8]])

In [43]:
q.argmax(axis=1)

array([2, 2, 0])

### Type casting

In [42]:
z.dtype

dtype('int64')

In [44]:
z = z.astype('f') # Casting into another data type
print(z)
z.dtype

[[ 4.  5.  6.]
 [16. 25. 36.]]


dtype('float32')

## 2D Axis

In [45]:
a = np.array([-4,-3,-1,5,19])
b = np.array([[1,99,20,31],[-1,-24,37,-13],[-7,11,49,4]])

In [46]:
print(a)
print('-'*20)
print(b)

[-4 -3 -1  5 19]
--------------------
[[  1  99  20  31]
 [ -1 -24  37 -13]
 [ -7  11  49   4]]


In [47]:
print(a)
print("Max:", a.max())
print("Min:", a.min())
print("Mean:", a.mean())
print("Std:", a.std())
print("Index of Max Value:", a.argmax())
print("Max Value", a[a.argmax()])
print("Index of Min Value:", a.argmin())

[-4 -3 -1  5 19]
Max: 19
Min: -4
Mean: 3.2
Std: 8.49470423263812
Index of Max Value: 4
Max Value 19
Index of Min Value: 0


In [48]:
b.shape

(3, 4)

In [50]:
b.flatten().shape
print(b)

[[  1  99  20  31]
 [ -1 -24  37 -13]
 [ -7  11  49   4]]


In [51]:
print(b, end='\n\n')

print("Max:", b.max())
print("Min:", b.min())
print("Mean:", b.mean())
print("Std:", b.std())
print("Index of Max Value:", b.argmax()) # Returns position of the flattened
print("Index of Min Value:", b.argmin())

print('\n\n-- ALONG AXIS 0 --')
print("Max:", b.max(axis=0))
print("Min:", b.min(axis=0))
print("Mean:", b.mean(axis=0))
print("Std:", b.std(axis=0))
print("Index of Max Value:", b.argmax(axis=0)) # Returns position of the flattened
print("Index of Min Value:", b.argmin(axis=0))
print(b)
print('\n-- ALONG AXIS 1 --')
print("Max:", b.max(axis=1))
print("Min:", b.min(axis=1))
print("Mean:", b.mean(axis=1))
print("Std:", b.std(axis=1))
print("Index of Max Value:", b.argmax(axis=1)) # Returns position of the flattened
print("Index of Min Value:", b.argmin(axis=1))

[[  1  99  20  31]
 [ -1 -24  37 -13]
 [ -7  11  49   4]]

Max: 99
Min: -24
Mean: 17.25
Std: 32.00813698629355
Index of Max Value: 1
Index of Min Value: 5


-- ALONG AXIS 0 --
Max: [ 1 99 49 31]
Min: [ -7 -24  20 -13]
Mean: [-2.33333333 28.66666667 35.33333333  7.33333333]
Std: [ 3.39934634 51.74510175 11.8977122  18.11690432]
Index of Max Value: [0 0 2 0]
Index of Min Value: [2 1 0 1]
[[  1  99  20  31]
 [ -1 -24  37 -13]
 [ -7  11  49   4]]

-- ALONG AXIS 1 --
Max: [99 37 49]
Min: [  1 -24  -7]
Mean: [37.75 -0.25 14.25]
Std: [36.95520938 22.99320552 21.0638909 ]
Index of Max Value: [1 2 2]
Index of Min Value: [0 1 0]


## Indexing & Slicing
#### Slicing => Viewing

In [52]:
a = np.arange(0,13,1)
a = a**2
# a = np.arange(13)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [53]:
a[0], a[4], a[0:3:2]

(0, 16, array([0, 4]))

In [54]:
a[::-1]

array([144, 121, 100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0])

In [55]:
a[-4:]

array([ 81, 100, 121, 144])

In [64]:
a
a[::-2]

array([144, 100,  64,  36,  16,   4,   0])

In [57]:
a[-5:0:-2]

array([64, 36, 16,  4])

In [58]:
r = np.arange(36)
print(r)
r.resize((6,6))
r

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [59]:
print(r[2,2]) # Second row, second column
print(r[2][2])
print(r[2])
'''
    Notice the ',' usage while indexing as compared to [][] usage to access multidimensional lists
'''

14
14
[12 13 14 15 16 17]


"\n    Notice the ',' usage while indexing as compared to [][] usage to access multidimensional lists\n"

In [60]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [61]:
r[3:5, -2:]

array([[22, 23],
       [28, 29]])

In [62]:
r[:2,3]

array([3, 9])

In [63]:
# Every second element from the last row
r[-1, ::-2]

array([35, 33, 31])

## Conditonal Indexing (Index Arrays)

In [65]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [66]:
verdict = r>30
print(r)
verdict

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False,  True,  True,  True,  True,  True]])

In [67]:
greater_than_30 = r[verdict]
greater_than_30

array([31, 32, 33, 34, 35])

In [68]:
print(r)
print(verdict)
print((r>30).sum())
print((r[r>30]).sum())

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False  True  True  True  True  True]]
5
165


In [69]:
# Assigning the elements greater than 30 to a new value
r[r > 30] = 99
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 99, 99, 99, 99, 99]])

In [70]:
r2 = r[:3, :3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [71]:
r2[0,0] = 100

In [73]:
print(r)
r2

[[100   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22  23]
 [ 24  25  26  27  28  29]
 [ 30  99  99  99  99  99]]


array([[100,   1,   2],
       [  6,   7,   8],
       [ 12,  13,  14]])

### + vs +=

In [74]:
a = np.array([1,2,3,4])
b = a
a += np.array([1,1,1,1])  # inplace
print('a:', a)
print('b:', b)

a: [2 3 4 5]
b: [2 3 4 5]


In [76]:
a = np.array([1,2,3,4])
b = a
print(id(a))
print(id(b))
a = a + np.array([1,1,1,1])
print('a:', a)
print('b:', b)
print(id(a))
print(id(b))

4712687696
4712687696
a: [2 3 4 5]
b: [1 2 3 4]
4712723520
4712687696


## Copying

In [77]:
r2[:] = 0
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 99, 99, 99, 99, 99]])

In [78]:
rc = r.copy()
rc

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 99, 99, 99, 99, 99]])

In [79]:
rc[rc < 3] = 3

In [80]:
rc

array([[ 3,  3,  3,  3,  4,  5],
       [ 3,  3,  3,  9, 10, 11],
       [ 3,  3,  3, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 99, 99, 99, 99, 99]])

In [81]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 99, 99, 99, 99, 99]])

## Iterating

In [83]:
import random
print(random.randint(0,10))
test = np.random.randint(0, 10, (4,3))
test

2


array([[1, 1, 6],
       [1, 6, 2],
       [4, 1, 9],
       [2, 4, 2]])

In [84]:
for row in test:
    print(row)

[1 1 6]
[1 6 2]
[4 1 9]
[2 4 2]


In [87]:
for index in range(len(test)):
    print("Row {} is {}".format(index, test[index]))

Row 0 is [1 1 6]
Row 1 is [1 6 2]
Row 2 is [4 1 9]
Row 3 is [2 4 2]


In [88]:
for i, row in enumerate(test):
        print("Row {} is {}".format(i, row))

Row 0 is [1 1 6]
Row 1 is [1 6 2]
Row 2 is [4 1 9]
Row 3 is [2 4 2]


In [89]:
test2 = test**2
test2

array([[ 1,  1, 36],
       [ 1, 36,  4],
       [16,  1, 81],
       [ 4, 16,  4]])

In [90]:
for i,j in zip(test, test2):
    print(i, '+', j, '=', i+j)

[1 1 6] + [ 1  1 36] = [ 2  2 42]
[1 6 2] + [ 1 36  4] = [ 2 42  6]
[4 1 9] + [16  1 81] = [20  2 90]
[2 4 2] + [ 4 16  4] = [ 6 20  6]


In [98]:
list(zip(test, test2))

[(array([1, 1, 6]), array([ 1,  1, 36])),
 (array([1, 6, 2]), array([ 1, 36,  4])),
 (array([4, 1, 9]), array([16,  1, 81])),
 (array([2, 4, 2]), array([ 4, 16,  4]))]

In [99]:
list = list()
list()

TypeError: 'list' object is not callable

In [100]:
print(list)

[]


In [97]:
print("hello","world")

hello world
